

---

- name: install nginx
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: install nginx package
      package:
           name: install nginx
           state: present
           update_cache: true
    - name: start nginx service
      service:
           name: nginx
           state: started
           enabled: true
 
